language: python

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

install: 
    - pip install pyserial
    - git submodule update --init --recursive
    - python setup.py install

matrix:
    allow_failures:
        - python: 3.3
        - python: 3.4
        - python: 3.5

script: python -m unittest discover -v sunspec

notifications:
    email: false
